.MODEL SMALL   
.STACK 100H
.CODE
.DATA 
MSG1 DB 'ENTER A CHARACTER:$'
MSG2 DB 'YOU HAVE ENTERED:$ '

MAIN PROC  
    MOV AX, @DATA
    MOV DS, AX
    ;PRINT MSG1
    LEA DX, MSG1
    MOV AH, 9
    INT 21H
    ;DISPLAY A SINGLE CHARACTER
    ;MOV AH, 2
    ;MOV DL, '?'
    ;INT 21H  
    
    ;ASK FOR A SINGLE CHARACTER INPUT. THE ASCII CODE OF THE CHARACTER WILL BE CONSIDERED.
    ;THE INPUT WILL AUTOMATICALLY BE STORED IN AL
    MOV AH, 1
    INT 21H  
    
    ;MOV THE INPUT FROM AL TO A SAFE REGISTER. 
    MOV BL, AL   
    
    
    ;GO TO A NEW LINE. WE NEED TO PRINT TWO SPECIAL CHARACTERS - CARRIAGE RETURN: 0DH AND LINE FEED:OAH
    MOV AH, 2
    MOV DL, 0DH
    INT 21H 
    MOV DL, 0AH
    INT 21H
    ;NOTICE HOW WE PRINT TWO CHARACTERS ONE AFTER THE OTHER WITHOUT CALLING THE PRINT FUNCTION TWICE
    
    ;PRINT MSG2
    LEA DX, MSG2
    MOV AH, 9
    INT 21H
    
    ;DISPLAY THE CHARACTER WE HAVE JUST TAKEN AS INPUT. REMEMBER, YOU HAD MOVED THE INPUT CHARACTER INTO BL
    MOV AH, 2
    MOV DL, BL
    INT 21H
    
    ;FINALLY, END YOUR PROGRAM WITH THE FOLLOWING 'FORMALITY'
    MOV AH, 4CH
    INT 21H
    
    
MAIN ENDP
    END MAIN
            
            