.MODEL SMALL   
.STACK 100H
.CODE  
.DATA
MSG1 DB 'HELLO WORLD$'
MSG2 DB 'ENTER A NUMBER:$'
MSG3 DB 'YOU HAVE ENTERED:$'  
MSG4 DB 'THE SUM IS:$'

MAIN PROC  
    MOV AX, @DATA
    MOV DS, AX ;sending the address of data segment to the DS register
    
    ;DISPLAY MSG1
    LEA DX, MSG1
    MOV AH, 9
    INT 21H   
    
    ;DISPLAY MSG2 IN THE NEXT LINE
    ;DISPLAY A NEW LINE AT FIRST
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    ;NOW DISPLAY MSG2
    LEA DX, MSG2
    MOV AH, 9
    INT 21H
    
    ;NOW LET'S ACTUALLY TAKE A NUMBER INPUT
    MOV AH, 1
    INT 21H
    SUB AL, 30H ;WE ARE TAKING A NUMBER AS INPUT, SO REMEMBER TO SUBTRACT 30H
    MOV BL, AL ; MOVE THE NUMBER TO A SAFE REGISTER
    
    ;DISPLAY A NEW LINE AT FIRST
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    
    ;NOW LET'S ACTUALLY TAKE A 2nd NUMBER INPUT
    MOV AH, 1
    INT 21H
    SUB AL, 30H ;WE ARE TAKING A NUMBER AS INPUT, SO REMEMBER TO SUBTRACT 30H
    MOV CL, AL ; MOVE THE NUMBER TO A SAFE REGISTER
               
    ;ADD THE TWO INPUT NUMBERS
    ADD BL, CL
               
    ;DISPLAY A NEW LINE AT FIRST
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    
    ;NOW DISPLAY MSG4
    LEA DX, MSG4
    MOV AH, 9
    INT 21H
    
    ;LETS DISPLAY THE NUMBER WE HAVE INPUT NOW 
    ;IF WE SIMPLY PRINT BL, WE WILL NOT SEE THE NUMBER. THE OUTPUT FUNCTION ACTUALLY CONSIDERS THE NUMBER IT PRINTS TO BE AN ASCII
    ;THEREFORE, IT PRINTS OUT THE CORRESPONDING ASCII SYMBOL. TRY THE FOLLOWING: 
    ADD BL, 30H
    MOV AH, 2
    MOV DL, BL
    INT 21H
     
    
    ;FINALLY, END YOUR PROGRAM WITH THE FOLLOWING 'FORMALITY'
    MOV AH, 4CH
    INT 21H
    
    
MAIN ENDP
    END MAIN
            
            